services:
  nginx:
    image: l4ksh1928/tdsnginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:            
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf  
      - ./proxy/frontend:/usr/share/nginx/html
    depends_on:
      - app1
      - app2
    networks:
      - tds
    deploy:
      resources:
        limits:
          memory: 128M

  db:
    image: mysql:8.0-debian
    container_name: db
    volumes:
      - tds_db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_files:
      - .env
    networks:
      - tds
    deploy:
      resources:
        limits:
          memory: 512M

  app1:
    image: l4ksh1928/tds:latest
    container_name: app1
    env_files:
      - .env
    depends_on:
      - db
    networks:
      - tds
    deploy:
      resources:
        limits:
          memory: 128M

  app2:
    image: l4ksh1928/tds:latest
    container_name: app2
    env_files:
      - .env
    depends_on:
      - db
    networks:
      - tds
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  tds:
    driver: bridge

volumes:
  tds_db:                 
